language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - v2
notifications:
  email: false
node_js:
  - '7'
script:
  - yarn test:coverage
  - yarn build
after_success:
  - yarn report-coverage
