language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - v2.0.0
notifications:
  email: false
node_js:
  - '7'
  - '6'
script:
  - yarn test:coverage
after_success:
  - yarn report-coverage
